[package]
name = "git-remote-fetcher"
version = "0.1.0"
authors = ["Marais Rossouw <me@maraisr.com>"]
publish = false
edition = "2018"

[profile.release]
lto = true
panic = "abort"

[dependencies]
clap = "2.33.0"