name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # TODO: Add macos-latest and windows-latest also
    env:
      TZ: Australia/Brisbane
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: target/
          key: ${{ matrix.os }}-${{ hashFiles('Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: GitRemoteFetcher-${{ matrix.os }}
          path: target/release/