name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      TZ: Australia/Brisbane
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: target/
          key: ${{ matrix.os }}-${{ hashFiles('Cargo.lock') }}
      - name: Install Rust (rustup)
        run: |
          rustup update stable
          rustup default stable
        if: matrix.os != 'macos-latest'
      - name: Install Rust (macos)
        run: |
          curl https://sh.rustup.rs | sh -s -- -y
          echo "##[add-path]$HOME/.cargo/bin"
        if: matrix.os == 'macos-latest'
      - run: cargo build --verbose --release
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: GitRemoteFetcher-${{ matrix.os }}
          path: target/release/
